// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/adapter/slackcontroller/setcontroller.go

// Package slackcontroller is a generated GoMock package.
package slackcontroller

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSetRequestHandler is a mock of SetRequestHandler interface
type MockSetRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSetRequestHandlerMockRecorder
}

// MockSetRequestHandlerMockRecorder is the mock recorder for MockSetRequestHandler
type MockSetRequestHandlerMockRecorder struct {
	mock *MockSetRequestHandler
}

// NewMockSetRequestHandler creates a new mock instance
func NewMockSetRequestHandler(ctrl *gomock.Controller) *MockSetRequestHandler {
	mock := &MockSetRequestHandler{ctrl: ctrl}
	mock.recorder = &MockSetRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSetRequestHandler) EXPECT() *MockSetRequestHandlerMockRecorder {
	return m.recorder
}

// Handler mocks base method
func (m *MockSetRequestHandler) Handler(ctx context.Context, data EventCallbackData) *Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler", ctx, data)
	ret0, _ := ret[0].(*Response)
	return ret0
}

// Handler indicates an expected call of Handler
func (mr *MockSetRequestHandlerMockRecorder) Handler(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockSetRequestHandler)(nil).Handler), ctx, data)
}
