// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/adapter/slackcontroller/urlverificationcontroller.go

// Package slackcontroller is a generated GoMock package.
package slackcontroller

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUrlVerificationRequestHandler is a mock of UrlVerificationRequestHandler interface
type MockUrlVerificationRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUrlVerificationRequestHandlerMockRecorder
}

// MockUrlVerificationRequestHandlerMockRecorder is the mock recorder for MockUrlVerificationRequestHandler
type MockUrlVerificationRequestHandlerMockRecorder struct {
	mock *MockUrlVerificationRequestHandler
}

// NewMockUrlVerificationRequestHandler creates a new mock instance
func NewMockUrlVerificationRequestHandler(ctrl *gomock.Controller) *MockUrlVerificationRequestHandler {
	mock := &MockUrlVerificationRequestHandler{ctrl: ctrl}
	mock.recorder = &MockUrlVerificationRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUrlVerificationRequestHandler) EXPECT() *MockUrlVerificationRequestHandlerMockRecorder {
	return m.recorder
}

// Handler mocks base method
func (m *MockUrlVerificationRequestHandler) Handler(ctx context.Context, data EventCallbackData) *Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler", ctx, data)
	ret0, _ := ret[0].(*Response)
	return ret0
}

// Handler indicates an expected call of Handler
func (mr *MockUrlVerificationRequestHandlerMockRecorder) Handler(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockUrlVerificationRequestHandler)(nil).Handler), ctx, data)
}
