// Code generated by MockGen. DO NOT EDIT.
// Source: controllerhandler.go

// Package settime is a generated GoMock package.
package settime

import (
	reflect "reflect"
	appcontext "slacktimer/internal/app/util/appcontext"

	gomock "github.com/golang/mock/gomock"
)

// MockControllerHandler is a mock of ControllerHandler interface
type MockControllerHandler struct {
	ctrl     *gomock.Controller
	recorder *MockControllerHandlerMockRecorder
}

// MockControllerHandlerMockRecorder is the mock recorder for MockControllerHandler
type MockControllerHandlerMockRecorder struct {
	mock *MockControllerHandler
}

// NewMockControllerHandler creates a new mock instance
func NewMockControllerHandler(ctrl *gomock.Controller) *MockControllerHandler {
	mock := &MockControllerHandler{ctrl: ctrl}
	mock.recorder = &MockControllerHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockControllerHandler) EXPECT() *MockControllerHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method
func (m *MockControllerHandler) Handle(ac appcontext.AppContext, input HandleInput) *Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ac, input)
	ret0, _ := ret[0].(*Response)
	return ret0
}

// Handle indicates an expected call of Handle
func (mr *MockControllerHandlerMockRecorder) Handle(ac, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockControllerHandler)(nil).Handle), ac, input)
}
