version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: "/var/lib/postgresql/data/pgdata"
#  mongodb:
#    image: mongo:4.4
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./tmp/mongodb:/var/log
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#      MONGO_INITDB_DATABASE: admin
