-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS test_timer_event (
    user_id character varying(9) PRIMARY KEY,
    notification_time_utc timestamp without time zone,
    interval_min integer NOT NULL DEFAULT 0
);
