version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  test:
    docker:
      - image: circleci/golang:1.15.2

    working_directory: /go/src/github.com/takakd/slacktimer
    steps:
      - checkout
      # Get tools.
      - run: go get -u golang.org/x/tools/cmd/goimports
      - run: go get -u golang.org/x/lint/golint
      # Format, imports, lint, vet, and test.
      - run: go fmt ./...
      - run: goimports -w $(find . -type f -name "*.go" -not -path "./vendor/*")
      - run: golint ./cmd/... ./internal/...
      - run: go vet ./cmd/... ./internal/...
      - run: go mod vendor
      - run: go test -v ./...
      # Send status to slack.
      - slack/status:
          success_message: "Test is OK.🤗"
          failure_message: "Test Failed.🥺"
          webhook: $SLACK_WEBHOOK

workflows:
  test:
    jobs:
      - test
