# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.15.2

    working_directory: /go/src/github.com/takakd/slacktimer
    steps:
      - checkout
      # Format, imports, lint, vet, and test.
      - run: go fmt ./...
      - run: goimports -w $(find . -type f -name "*.go" -not -path "./vendor/*")
      - run: golint ./cmd/... ./internal/...
      - run: go vet ./cmd/... ./internal/...
      - run: go mod vendor
      - run: go test -v ./...
      # Send status to slack.
      - slack/status:
          success_message: "Test is OK.🤗"
          failure_message: "Test Failed.🥺"
          webhook: $SLACK_WEBHOOK
orbs:
  slack: circleci/slack@3.4.2