// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/usecase/enqueueevent/repository.go

// Package enqueueevent is a generated GoMock package.
package enqueueevent

import (
	context "context"
	reflect "reflect"
	enterpriserule "slacktimer/internal/app/enterpriserule"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindTimerEventsByTime mocks base method
func (m *MockRepository) FindTimerEventsByTime(ctx context.Context, eventTime time.Time) ([]*enterpriserule.TimerEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTimerEventsByTime", ctx, eventTime)
	ret0, _ := ret[0].([]*enterpriserule.TimerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTimerEventsByTime indicates an expected call of FindTimerEventsByTime
func (mr *MockRepositoryMockRecorder) FindTimerEventsByTime(ctx, eventTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTimerEventsByTime", reflect.TypeOf((*MockRepository)(nil).FindTimerEventsByTime), ctx, eventTime)
}

// SaveTimerEvent mocks base method
func (m *MockRepository) SaveTimerEvent(ctx context.Context, event *enterpriserule.TimerEvent) (*enterpriserule.TimerEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTimerEvent", ctx, event)
	ret0, _ := ret[0].(*enterpriserule.TimerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTimerEvent indicates an expected call of SaveTimerEvent
func (mr *MockRepositoryMockRecorder) SaveTimerEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTimerEvent", reflect.TypeOf((*MockRepository)(nil).SaveTimerEvent), ctx, event)
}
