// Code generated by MockGen. DO NOT EDIT.
// Source: ./controller.go

// Package enqueue is a generated GoMock package.
package enqueue

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockController is a mock of Controller interface
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Handle mocks base method
func (m *MockController) Handle(ctx context.Context, input HandleInput) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", ctx, input)
}

// Handle indicates an expected call of Handle
func (mr *MockControllerMockRecorder) Handle(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockController)(nil).Handle), ctx, input)
}
