// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/adapter/enqueuecontroller/handler.go

// Package enqueuecontroller is a generated GoMock package.
package enqueuecontroller

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockEventHandler is a mock of EventHandler interface
type MockEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler
type MockEventHandlerMockRecorder struct {
	mock *MockEventHandler
}

// NewMockEventHandler creates a new mock instance
func NewMockEventHandler(ctrl *gomock.Controller) *MockEventHandler {
	mock := &MockEventHandler{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEventHandler) EXPECT() *MockEventHandlerMockRecorder {
	return m.recorder
}

// Handler mocks base method
func (m *MockEventHandler) Handler(ctx context.Context) *HandlerResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler", ctx)
	ret0, _ := ret[0].(*HandlerResponse)
	return ret0
}

// Handler indicates an expected call of Handler
func (mr *MockEventHandlerMockRecorder) Handler(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockEventHandler)(nil).Handler), ctx)
}
