// Code generated by MockGen. DO NOT EDIT.
// Source: ./api.go

// Package slack is a generated GoMock package.
package slack

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAPI is a mock of API interface
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// ConversationsOpen mocks base method
func (m *MockAPI) ConversationsOpen(userId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConversationsOpen", userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConversationsOpen indicates an expected call of ConversationsOpen
func (mr *MockAPIMockRecorder) ConversationsOpen(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConversationsOpen", reflect.TypeOf((*MockAPI)(nil).ConversationsOpen), userId)
}

// ChatPostMessage mocks base method
func (m *MockAPI) ChatPostMessage(channelId, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatPostMessage", channelId, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatPostMessage indicates an expected call of ChatPostMessage
func (mr *MockAPIMockRecorder) ChatPostMessage(channelId, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatPostMessage", reflect.TypeOf((*MockAPI)(nil).ChatPostMessage), channelId, message)
}
