// Code generated by MockGen. DO NOT EDIT.
// Source: inputport.go

// Package notifyevent is a generated GoMock package.
package notifyevent

import (
	reflect "reflect"
	appcontext "slacktimer/internal/app/util/appcontext"

	gomock "github.com/golang/mock/gomock"
)

// MockInputPort is a mock of InputPort interface
type MockInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockInputPortMockRecorder
}

// MockInputPortMockRecorder is the mock recorder for MockInputPort
type MockInputPortMockRecorder struct {
	mock *MockInputPort
}

// NewMockInputPort creates a new mock instance
func NewMockInputPort(ctrl *gomock.Controller) *MockInputPort {
	mock := &MockInputPort{ctrl: ctrl}
	mock.recorder = &MockInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInputPort) EXPECT() *MockInputPortMockRecorder {
	return m.recorder
}

// NotifyEvent mocks base method
func (m *MockInputPort) NotifyEvent(ac appcontext.AppContext, input InputData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyEvent", ac, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyEvent indicates an expected call of NotifyEvent
func (mr *MockInputPortMockRecorder) NotifyEvent(ac, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyEvent", reflect.TypeOf((*MockInputPort)(nil).NotifyEvent), ac, input)
}
